### ISSUE TITLE
BUG: UnicodeEncodeError: 'charmap' codec can't encode character '\u0141'

### ISSUE THREAD

**Issue by jatoledo** [oeg-upm/morph-kgc#68]
####  What Happens?
Hi, I'm using Morph-kgc and I have the error:
```bash
UnicodeEncodeError: 'charmap' codec can't encode character '\u0141' in position 133: character maps to <undefined>
```

```bash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\site-packages\morph_kgc\__main__.py", line 21, in <module>
    process_materialization(mappings, config)
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\site-packages\morph_kgc\engine.py", line 46, in process_materialization
    materializer.materialize_concurrently()
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\site-packages\morph_kgc\materializer.py", line 407, in materialize_concurrently
    num_triples = sum(pool.starmap(_materialize_mapping_partition,
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\jhon\anaconda3\envs\ERA-KGG\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
UnicodeEncodeError: 'charmap' codec can't encode character '\u0141' in position 133: character maps to <undefined>
```

#### Environment (please complete the following information):

 - Morph-KGC version: 2.0.1

**Comment by jatoledo** [comment]
It works!
